### ISSUE TITLE
Allow the user to provide ML config info in a properties file or command line

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/data-hub-in-a-box#21]
Allow the user to specify ML properties (host, port, user, password) in a properties file. The quickstart jar, upon launch, should check for the existence of this file. If it exists it should populate the login screen with the values.

If the file does not exist then it should populate the login fields with default values (localhost, port, admin, admin)

Also let the user pass in these same properties (host, port, user, password) via the command line when running:

```bash
java -jar quickstart.jar ....
```

**Comment by jmakeig** [comment]
You should think about a way to externalize passwords too. In a production environment there shouldn’t be clear-text passwords anywhere in config, code, etc. We should push this down into dev environments as the default behavior as well.

**Comment by maeisabelle** [comment]
Hi @paxtonhare and @jmakeig! 

Since we want to persist the username, password, host, port, etc., would you like to setup Quickstart in such a way where the user needs to sign in and sign out using the username and password he/she's using in MarkLogic. That way, the data are persisted in a session and a cookie until the user signs out.

**Comment by gmarintes** [comment]
The ML host, username and password are things we always need in order to work with a MarkLogic server. If we could have the user "login", we can save those information in a session (as Mae proposed) and we can avoid asking the user for those information every time we need it. We can also save the ML host and username in a cookie or local storage so we can pre-propulate the login page with those information the next time the user uses quick-start.
Thoughts?

**Comment by paxtonhare** [comment]
I just updated the ticket to be pretty much a different ticket.
